{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-app-chart.redis.fullname" . }}
  labels:
    {{- include "my-app-chart.redis.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.redis.replicaCount }}
  selector:
    matchLabels:
      {{- include "my-app-chart.redis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "my-app-chart.redis.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: redis
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
        imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
        ports:
        - name: redis
          containerPort: {{ .Values.redis.service.targetPort }}
          protocol: TCP
        livenessProbe:
          {{- toYaml .Values.redis.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.redis.readinessProbe | nindent 10 }}
        resources:
          {{- toYaml .Values.redis.resources | nindent 10 }}
        volumeMounts:
        {{- if .Values.redis.persistence.enabled }}
        - name: redis-data
          mountPath: /data
        {{- end }}
      volumes:
      {{- if .Values.redis.persistence.enabled }}
      - name: redis-data
        persistentVolumeClaim:
          claimName: {{ include "my-app-chart.redis.fullname" . }}-pvc
      {{- end }}
      {{- with .Values.redis.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

