{{- if .Values.secrets.jwt.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-app-chart.jwt.secretName" . }}
  labels:
    {{- include "my-app-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.secrets.jwt.secret | quote }}
  jwt-refresh-secret: {{ .Values.secrets.jwt.refreshSecret | quote }}
{{- end }}

