{{- if .Values.secrets.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-app-chart.postgresql.secretName" . }}
  labels:
    {{- include "my-app-chart.postgresql.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.auth.secretKeys.userPasswordKey }}
  {{ .Values.postgresql.auth.secretKeys.userPasswordKey }}: {{ .Values.secrets.postgresql.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.postgresql.auth.secretKeys.adminPasswordKey }}
  {{ .Values.postgresql.auth.secretKeys.adminPasswordKey }}: {{ .Values.secrets.postgresql.adminPassword | b64enc | quote }}
  {{- end }}
  postgres-password: {{ .Values.secrets.postgresql.password | b64enc | quote }}
{{- end }}

