{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-app-chart.postgresql.fullname" . }}
  labels:
    {{- include "my-app-chart.postgresql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "my-app-chart.postgresql.selectorLabels" . | nindent 4 }}
{{- end }}

